// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("ExampleApp")]
[assembly: AssemblyDescriptionAttribute("ExampleApp")]
[assembly: GuidAttribute("dd5319ab-a791-4164-af39-e79915f198b2")]
[assembly: AssemblyProductAttribute("ExampleApp")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
