// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("ExampleApp")]
[assembly: AssemblyDescriptionAttribute("ExampleApp")]
[assembly: GuidAttribute("079e6ad9-6706-4e1c-92c5-629173fcb67c")]
[assembly: AssemblyProductAttribute("ExampleApp")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
